### ISSUE TITLE
“当客户端与nginx进行三次握手，与nginx建立好一个连接后” 这句话是否不太准确？

### ISSUE THREAD

**Issue by wangbin579** [taobao/nginx-book#19]
nginx是不负责tcp协议的三次握手的。

这段话出现在http://tengine.taobao.org/book/chapter_02.html

**Comment by zlsvn** [comment]
请问nginx是不负责tcp协议的三次握手的，是指nginx的代码没有处理tcp三次握手的报文的业务逻辑吗？多谢，
