### ISSUE TITLE
请问下ngnix的handler里面将stdout重定向到哪里了？

### ISSUE THREAD

**Issue by wangyuzju** [taobao/nginx-book#272]
在读到 [http://tengine.taobao.org/book/chapter_03.html#hello-handler](http://tengine.taobao.org/book/chapter_03.html#hello-handler) 这篇文章的时候，做了下试验

关闭了deamon模式将error_log重定向到stderr之后，能在控制台直接看到输出到stderr中的内容，却没有办法看到输出到stdout中的内容。
```
static ngx_int_t ngx_http_hello_handler(ngx_http_request_t *r)
{
    // 没有任何反应
    printf("hello world!");
    // 可以输出
    fptinft(stderr, "hello world!");
}
```
请问下各位，nginx是如何重定向一个请求访问时候的stdout的，或者是整个程序的stdout？

我的conf文件
```
daemon off;
master_process  off;
error_log stderr info
```

**Comment by chobits** [comment]
这个问题已经在https://github.com/alibaba/tengine/issues/521 得到回复。
故关闭，如果问题可以再次开启该问题。
