### ISSUE TITLE
关于内存池分配问题

### ISSUE THREAD

**Issue by gancaocao** [taobao/nginx-book#291]
大家好 ， 我看nginx内存分配时 发现 如果当前内存池不够分配就调用ngx_palloc_block创建一个新的pool
但是发现这个新的pool跟开始的那个不一样，新的pool的数据起始位置在ngx_pool_data_t后面 ， 但是看网上博客时的图解时却是创建了一个完全一样的pool ， 不知道是不是我读错了

**Comment by chobits** [comment]
这个问题已经在https://github.com/taobao/nginx-book/issues/290得到回复。
故关闭之。如有问题可以再次开启该问题。
