### ISSUE TITLE
nginx平台初探(100%)¶ ngx_list_t *ngx_list_create(ngx_pool_t *pool, ngx_uint_t n, size_t size);

### ISSUE THREAD

**Issue by zieckey** [taobao/nginx-book#294]
current content:
n:	每个节点固定长度的数组的长度。
size:	存放的具体元素的个数。
 
advice:
n:	每个节点(ngx_list_part_t)最多可以存放的元素个数
size:	每个元素所占用的内存大小

reason:
描述更准确

**Comment by chobits** [comment]
Thanks for your report.
Fixed in https://github.com/taobao/nginx-book/pull/304.
