### ISSUE TITLE
nginx平台初探(100%)¶ ngx_int_t ngx_strcasecmp(u_char *s1, u_char *s2);

### ISSUE THREAD

**Issue by lineves** [taobao/nginx-book#355]
current content:
 定义变量时，使用ngx_null_string初始化字符串为空字符串，符串的长度为0，data为NULL。
advice:
加一个字
reason:
 少一个字

**Comment by chobits** [comment]
感谢反馈，最近有个commit已经修复了该问题：https://github.com/taobao/nginx-book/pull/351.
