### ISSUE TITLE
nginx平台初探(100%)¶ while (true) {    for t in run_tasks:        t.handler();    update_time(&amp;now);    timeout =...

### ISSUE THREAD

**Issue by liaojieliang** [taobao/nginx-book#356]
current content:放在一颗维护定时器的红黑树里面
 ...
advice:放在一棵维护定时器的红黑树里面
 ...
reason:typo
 ...

**Comment by chobits** [comment]
感谢纠错，已经修复在此：https://github.com/taobao/nginx-book/commit/1c18fe22081d1aa063d37d82a27e6e2f0e877cc5
