### ISSUE TITLE
nginx平台初探(100%)¶ void *ngx_hash_find_wc_tail(ngx_hash_wildcard_t *hwc, u_char *name, size_t len);

### ISSUE THREAD

**Issue by MGmoket** [taobao/nginx-book#366]
current content:
参数及返回值请参加上个函数的说明。
advice:
参数及返回值请参见上个函数的说明。
reason:
 错字

**Comment by chobits** [comment]
感谢，已经修复在这里：https://github.com/taobao/nginx-book/pull/367
